app_admin_activity:
    path: /admin/activity
    controller: App\Controller\Admin\ActivityController::index
    
app_admin_activity_page:
    path: /admin/activity/{id}
    controller: App\Controller\Admin\ActivityController::index
